<?php
/**
 * Created by PhpStorm.
 * User: jonas
 * Date: 21/04/18
 * Time: 15:02
 */

namespace AppBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use AppBundle\Entity\Recipe;
use AppBundle\Form\RecipeType;



class CrudRecipeController extends Controller
{

    /**
     * @Route("/ajout", name="addRecette")
     */

    //Ajouter une recette
    public function addreceiptAction(Request $request)
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');

        $recipe = new Recipe();

        $em = $this->getDoctrine()->getManager();

        $form = $this->createForm(RecipeType::class, $recipe);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // $file stores the uploaded jpg file
            /** @var Symfony/Component/HttpFoundation/File/UploadedFile $file */

            $file = $recipe->getImage();
            $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();
            // moves the file to the directory where images are stored
            $file->move(
                $this->getParameter('images_directory'),
                $fileName);
            //
            // updates the 'image' property to store the jpg file name
            // instead of its contents
            $recipe->setImage($fileName);
            //
            $em->persist($recipe);
            $em->flush();

            return $this->redirectToRoute('addRecette',array($recipe->getId()));

        }
        /*}*/

        $var['form'] = $form->createView();


        return $this->render('form.html.twig',$var);

    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }

    /**
     * @Route("/admin2", name="adminRecette")
     */
    //Administration2
    public function adminrecipeAction()
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');
        $em = $this->getDoctrine()->getManager();
        $rep = $em->getRepository('AppBundle:Recipe');

        $recette= $rep->findAll();
//
//
        return $this->render('admin2.html.twig', ['recette'=>$recette]);

    }
    /**
     * @Route("/liste", name="listRecette")
     */
    //Afficher la liste des recettes
    public function listrecipeAction()
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');
        $em = $this->getDoctrine()->getManager();
        $rep = $em->getRepository('AppBundle:Recipe');

        $recette= $rep->findAll();
//
//
        return $this->render('liste.html.twig', ['recette'=>$recette]);

    }

    /**
     * @Route("/liste/{id}", name="removeRecette")
     */
    //Supprimer une recette
    public function removereceiptAction(Recipe $recipe)
    {

        try {

            $em = $this->getDoctrine()->getManager();
            $lastImage = $recipe->getImage();
            unlink('uploads/images/'.$lastImage);


            $em->remove($recipe);
            $em->flush();


        } catch (Exception $exception) {
//            echo $exception;
        }


        return $this->redirectToRoute ('listRecette');
    }

    /**
     * @Route("/update/{id}", name="updateRecette")
     */
    //update
    public function updateFormAction(Request $request,$id)
    {

        $em = $this->getDoctrine()->getManager();
        $rep = $em->getRepository('AppBundle:Recipe');
        $recipe = $rep->find($id);

        $lastImage = $recipe->getImage();

        $form = $this->createForm(RecipeType::class,$recipe);


        if ($request->isMethod('Post')) {

            $form->handleRequest($request);
            if ($form->isValid()) {


                unlink('uploads/images/'.$lastImage);
                $file = $recipe->getImage();

                $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();
                // moves the file to the directory where images are stored
                $file->move(
                    $this->getParameter('images_directory'),
                    $fileName);
                //
                // updates the 'image' property to store the jpg file name
                // instead of its contents
                $recipe->setImage($fileName);

                $em->persist($recipe);
                $em->flush();




                //message ok

                return $this->redirectToRoute('listRecette');
                $this->addFlash('Ok_update','Mise à jour éffectuée');
            }
        }

        $var['form'] = $form->createView();
        return $this->render('update.html.twig', $var);

    }
    //Afficher les recettes
    /**
     * @Route("/recettes", name="showRecette")
     */
    public function showFormAction()
    {
        $em = $this->getDoctrine()->getManager();
        $rep = $em->getRepository('AppBundle:Recipe');

        $recipe= $rep->findAll();
//
//
//        $var['form'] = $form->createView();
        return $this->render('showRecettes.html.twig', ['recipe'=>$recipe]);
    }
}