<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAtcfqgq\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAtcfqgq/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerAtcfqgq.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerAtcfqgq\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerAtcfqgq\appProdProjectContainer(array(
    'container.build_hash' => 'Atcfqgq',
    'container.build_id' => 'a38bc35a',
    'container.build_time' => 1524472111,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerAtcfqgq');
