<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXbzqijl\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXbzqijl/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXbzqijl.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXbzqijl\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerXbzqijl\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Xbzqijl',
    'container.build_id' => '7f3d0d89',
    'container.build_time' => 1527064576,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerXbzqijl');
