<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6xqvcdu\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6xqvcdu/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container6xqvcdu.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container6xqvcdu\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container6xqvcdu\appDevDebugProjectContainer(array(
    'container.build_hash' => '6xqvcdu',
    'container.build_id' => '4e9ff312',
    'container.build_time' => 1529400221,
), __DIR__.\DIRECTORY_SEPARATOR.'Container6xqvcdu');
